## Perceptron

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
#Perceptron fn in sklearn uses hinge loss

In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
X = df.drop("lpa",axis = 1)

In [ ]:
y = df["lpa"]

In [ ]:
p = Perceptron()

In [ ]:
p.fit(X,y)

Perceptron()

In [ ]:
p.intercept_

array([ 0.,  0.,  1., -1.])

In [ ]:
p.coef_

array([[  7.,  -8.],
       [  2.,  -4.],
       [ -8.,   3.],
       [-17.,   8.]])

In [ ]:
## y = 7(8) + (-8)8 + 0
## and so on
## these are the final coeff, now using backpropogation to find weights


## Implementing MLP hard code


1. here we are initializing the number of parameters required.
2. if we have 2 input features and 3 nodes in hidden layer 1, then number parameters required in layer 1 = 2x3 = 6.
3. We have just formed arrays/ vectors of dimensions (l-1,l) for weights and (l,1) for bias.
4. Now, next step is to calculate the Weighted Sum.

In [ ]:
def initialize_param(layer_dims):
  np.random.seed(3)
  parameters = {}

  for l in range(1,len(layer_dims)):
    parameters["W"+str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters["b"+str(l)] = np.ones((layer_dims[l], 1))

  return parameters

In [ ]:
## check
initialize_param([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[1.],
        [1.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[1.]])}

1. From the output we can see that, the NN has 2 nodes in input layer, 2 nodes in hidden layer and 1 in output layer.
2. W1 has 2x2 shape => 4 weights.
3. 2 biases in layer 1
4. W2 has (2,1) => 2 weights
5. 1 bias.


In [ ]:
# Now we have to find the weighted sum
def linear_forward(A_prev, w, b):  # A_prev matrix is the output we get after a layer. eg A0 is the output we got from layer 1
   Z = np.dot(w.T, A_prev) + b

   return Z

In [ ]:
# Forward propogation
def L_forward(X, parameters):
  A = X
  num_layers = len(parameters)//2

  for i in range(1,num_layers+1):
    A_prev = A
    wi = parameters["W"+str(i)]
    bi = parameters["b"+str(i)]
    #print(f"A{i-1} =: ",A_prev)
    #print(f"w{i} =: ",wi)
    #print(f"b{i} =: ",bi)

    A = linear_forward(A_prev, wi,bi)
    #print("A"+str(i)+" =: ", A)


  return A, A_prev

1. Now, We have to find weighted sum and W1 has 2x2 shape for which X has to be something in form : (2,) for multiplication to hold.
2. X =: (2,1)
3. Z1 = wTX + b
4. A =: [z1,z2]T

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_param([2,2,1])

y_hat,A1 = L_forward(X, parameters)

A0 =:  [[8]
 [8]]
w1 =:  [[0.1 0.1]
 [0.1 0.1]]
b1 =:  [[1.]
 [1.]]
A1 =:  [[2.6]
 [2.6]]
A1 =:  [[2.6]
 [2.6]]
w2 =:  [[0.1]
 [0.1]]
b2 =:  [[1.]]
A2 =:  [[1.52]]


In [ ]:
y_hat, A1

(array([[1.52, 1.52, 1.52, 1.54]]),
 array([[2.6, 2.6, 2.6, 2.7],
        [2.6, 2.6, 2.6, 2.7]]))

In [ ]:
y_hat

array([[1.52]])

In [ ]:
A1

array([[2.6],
       [2.6]])

1. Now, we have to update the parameters using gradient descent algorithm

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_3926/332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipykernel_3926/332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipykernel_3926/332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.

In [ ]:
parameters

{'W1': array([[0.10447971, 0.10447971],
        [0.10447971, 0.10447971]]),
 'b1': array([[1.00055996],
        [1.00055996]]),
 'W2': array([[0.112896],
        [0.112896]]),
 'b2': array([[0.117856]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_param([2,2,1])

y_hat,A1 = L_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0 =:  [[8]
 [8]]
w1 =:  [[0.1 0.1]
 [0.1 0.1]]
b1 =:  [[1.]
 [1.]]
A1 =:  [[2.6]
 [2.6]]
A1 =:  [[2.6]
 [2.6]]
w2 =:  [[0.1]
 [0.1]]
b2 =:  [[1.]]
A2 =:  [[1.52]]


{'W1': array([[0.10447971, 0.10447971],
        [0.10447971, 0.10447971]]),
 'b1': array([[1.00055996],
        [1.00055996]]),
 'W2': array([[0.112896],
        [0.112896]]),
 'b2': array([[0.117856]])}

Now taking the next row

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0 =:  [[7]
 [9]]
w1 =:  [[0.10447971 0.10447971]
 [0.10447971 0.10447971]]
b1 =:  [[1.00055996]
 [1.00055996]]
A1 =:  [[2.67223538]
 [2.67223538]]
A1 =:  [[2.67223538]
 [2.67223538]]
w2 =:  [[0.112896]
 [0.112896]]
b2 =:  [[0.117856]]
A2 =:  [[0.72122537]]


{'W1': array([[0.11261235, 0.11493596],
        [0.11261235, 0.11493596]]),
 'b1': array([[1.00172177],
        [1.00172177]]),
 'W2': array([[0.13576379],
        [0.13576379]]),
 'b2': array([[0.14432134]])}

In [ ]:
# 3rd row
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0 =:  [[ 6]
 [10]]
w1 =:  [[0.11261235 0.11493596]
 [0.11261235 0.11493596]]
b1 =:  [[1.00172177]
 [1.00172177]]
A1 =:  [[2.80351937]
 [2.84069714]]
A1 =:  [[2.80351937]
 [2.84069714]]
w2 =:  [[0.13576379]
 [0.13576379]]
b2 =:  [[0.14432134]]
A2 =:  [[0.91060154]]


{'W1': array([[0.12264662, 0.13165975],
        [0.12266973, 0.13169827]]),
 'b1': array([[1.00339415],
        [1.003398  ]]),
 'W2': array([[0.16430024],
        [0.16467867]]),
 'b2': array([[0.17485746]])}

In [ ]:
# 4th row
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0 =:  [[ 5]
 [12]]
w1 =:  [[0.12264662 0.13165975]
 [0.12266973 0.13169827]]
b1 =:  [[1.00339415]
 [1.003398  ]]
A1 =:  [[3.08866408]
 [3.24207596]]
A1 =:  [[3.08866408]
 [3.24207596]]
w2 =:  [[0.16430024]
 [0.16467867]]
b2 =:  [[0.17485746]]
A2 =:  [[1.21622645]]


{'W1': array([[0.13421582, 0.15942582],
        [0.13436346, 0.1597632 ]]),
 'b1': array([[1.00570799],
        [1.00573674]]),
 'W2': array([[0.20002851],
        [0.20218153]]),
 'b2': array([[0.21374908]])}

Now, Here we have formed 1 code that is iterating over each row and calculating loss after each computation

In [ ]:
# epochs implementation

parameters = initialize_param([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())



Epoch -  1 Loss -  20.953081371180126
Epoch -  2 Loss -  13.073400503279615
Epoch -  3 Loss -  5.045019052331059
Epoch -  4 Loss -  1.7313550813127923
Epoch -  5 Loss -  1.2329784742733558


We can implement this structure wherever we like after changing loss function and adding activation function.

In [ ]:

# Utility Functions
def sigmoid(Z):

  A = 1/(1+np.exp(-Z))

  return A

In [ ]:
def update_parameters_for_actn(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))